### ISSUE TITLE
PVP and GM

### ISSUE THREAD

**Issue by Konsider** [TfT-02/Duel#44]
I have the config set to override WorldGuard's PVP setting but I still can't pvp (Latest spigot 1.8).

Also, can you stop people from going into GM 1 while duelling?

Thanks.

**Comment by Foreme** [comment]
Block the command?

**Comment by TfT-02** [comment]
As @Foreme suggests, you can add the command to this line https://github.com/TfT-02/Duel/blob/master/src/main/resources/config.yml#L41 in `config.yml`

**Comment by Konsider** [comment]
Thanks that solves the GM issue, but we still can't pvp.

**Comment by Konsider** [comment]
Ok I should have said I need it to force people OUT of gamemode 1

Also, this doesn't solve the "no pvp" issue, which is pretty vital.

**Comment by TfT-02** [comment]
Player's cannot duel when in creative mode
https://github.com/TfT-02/Duel/blob/master/src/main/java/com/me/tft_02/duel/util/player/DuelManager.java#L40

**Comment by Konsider** [comment]
They can on my server.

You keep avoiding the issue of the actual PVP not working either, which is kind of the point of your plugin.

No need to reply, I just won't be using it.

**Comment by TfT-02** [comment]
I'm not avoiding the issue, must've missed it. Normally a ticket is creating for one issue, not for two.

Anyways, as for this issue. When you enable the PVP override setting in duel, Duel will un-cancel any cancelled PVP event. E.g. some plugin prevents PVP, Duel allows it anyway. Though there are some cases where plugins do not use the proper way to handle PVP events, which makes it so that Duel cannot override them. Please check if you are not using any other plugins which prevent PVP, or if you have PVP disabled in the global server config (I believe this is still a thing, right?). I do know that WorldGuard handles the PVP events properly and that Duel is able to override them.

**Comment by Foreme** [comment]
I have pvp enabled in server properties and in Multiverse config but disabled in WorldGuard.

**Comment by Konsider** [comment]
@TfT-02 

Many thanks for the reply. I have quite a complicated server setup, and upon moving things around, changing settings etc I was finally able to get it all working :)
I appreciate your help in this matter, and hopefully my players will enjoy using your plugin!
Thanks,

Kon.

**Comment by TfT-02** [comment]
You're welcome, let me know if something else comes up. I will try to help as much as I can. ;)
